### ISSUE TITLE
incorrect content routing HTTP Request URL match condition regex

### ISSUE THREAD

**Issue by haught** [fortinet/fortiadc-ingress#10]
FortiADCIngressController: 2.0.0 (fortinet/fortiadc-ingress:2.0.0)
FortiADC-2000F v7.4.0,build0308,230706 (GA)

The content routing created for a prefix path rule does not appear to be correct. 

The the ingress spec of 
```yaml
spec:
  ingressClassName: fadc-ingress-controller
  rules:
  - host: test3.lab.example.net
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: test3-kuard-service
            port:
              number: 80
```
Creates a Content Routing entry with a **HTTP Request URL** regex of  ```^()((/\w+)|/|)+$``` and the problem with this is **\w** matches any word character - that excludes characters like *_* *.* *-* *?* *-* *&* etc... and as you can imagine this breaks all references to all files in the URL and any query parameters. Kinda important.

I would suggest changing the \w to simply a *.* to match any character. For example ```^()((/.+)|/|)+$``` .
